# This file describes a Fastly Compute@Edge package. To learn more visit:
# https://developer.fastly.com/reference/fastly-toml/

authors = ["macrometa.com"]
description = "Macrometa MetaFlix OTT App"
language = "javascript"
manifest_version = 2
name = "api-server"
service_id = ""

[local_server]
  [local_server.backends]
    [local_server.backends.gdn_url]
      url = "https://api-gdn.paas.macrometa.io"